name: flutter_travel
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  auto_route: ^0.6.7
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.12.0
  flutter_bloc: ^6.1.0
  get_it: ^4.0.2
  injectable: ^1.0.5
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  uuid: ^2.2.0
  kt_dart: ^0.7.0+1
  rxdart: ^0.24.1
  video_player: ^0.10.12+2
  flushbar: ^1.10.4




dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.2
  lint: ^1.2.0
  injectable_generator: ^1.0.6
  flutter_native_splash: ^0.1.9
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/

flutter_native_splash:
  image: images/splash.png
  color: "42a5f5"
  fill: true




